import { ContextualAction } from '../types';

export const ACTION_REGISTRY: ContextualAction[] = [
  {
    id: 'explain',
    label: 'Explain with AI',
    shortLabel: 'Explain',
    icon: '✨',
    description: 'Get a clear, academic breakdown of the selected text.',
    mobilePriority: 1,
    desktopPriority: 1,
    requiresAI: true,
  },
  {
    id: 'ask-ai',
    label: 'Ask AI Assistant',
    shortLabel: 'Ask AI',
    icon: '💬',
    description: 'Ask a specific question about this selection in the AI Chat.',
    mobilePriority: 2,
    desktopPriority: 2,
    requiresAI: true,
  },
  {
    id: 'generate-quiz',
    label: 'Generate Practice Quiz',
    shortLabel: 'Quiz',
    icon: '📝',
    description: 'Test yourself with generated mock exam questions.',
    allowedModules: ['notes', 'courses', 'chat'],
    mobilePriority: 3,
    desktopPriority: 3,
    requiresAI: true,
  },
  {
    id: 'create-flashcards',
    label: 'Create Flashcards',
    shortLabel: 'Flashcards',
    icon: '🃏',
    description: 'Generate active recall cards from the concept.',
    allowedModules: ['notes', 'courses', 'chat'],
    mobilePriority: 4,
    desktopPriority: 4,
    requiresAI: true,
  },
  {
    id: 'check-originality',
    label: 'Check Originality',
    shortLabel: 'Originality',
    icon: '🔍',
    description: 'Run plagiarism scans against academic indices.',
    allowedModules: ['assignments'],
    allowedRoles: ['faculty', 'admin'],
    mobilePriority: 5,
    desktopPriority: 5,
  },
  {
    id: 'assignment-feedback',
    label: 'Get AI Feedback',
    shortLabel: 'Feedback',
    icon: '📋',
    description: 'Analyze criteria and generate grading comments.',
    allowedModules: ['assignments'],
    mobilePriority: 6,
    desktopPriority: 6,
    requiresAI: true,
  },
  {
    id: 'explain-mistakes',
    label: 'Explain Mistakes',
    shortLabel: 'Mistakes',
    icon: '🧪',
    description: 'Break down incorrect steps in assignment evaluations.',
    allowedModules: ['assignments'],
    mobilePriority: 7,
    desktopPriority: 7,
    requiresAI: true,
  },
  {
    id: 'translate',
    label: 'Translate Selection',
    shortLabel: 'Translate',
    icon: '🌐',
    description: 'Translate this text into your preferred language.',
    mobilePriority: 8,
    desktopPriority: 8,
    requiresAI: true,
  },
  {
    id: 'listen-aloud',
    label: 'Listen Aloud',
    shortLabel: 'Listen',
    icon: '🔊',
    description: 'Synthesize speech from the selection.',
    mobilePriority: 9,
    desktopPriority: 9,
  },
  {
    id: 'bookmark',
    label: 'Bookmark Selection',
    shortLabel: 'Bookmark',
    icon: '🔖',
    description: 'Save this text to your Favorites collection.',
    mobilePriority: 10,
    desktopPriority: 10,
  },
  {
    id: 'add-study-plan',
    label: 'Add to Study Plan',
    shortLabel: 'Study Task',
    icon: '🗓️',
    description: 'Convert this topic into a weekly calendar study goal.',
    allowedRoles: ['student'],
    mobilePriority: 11,
    desktopPriority: 11,
  },
  {
    id: 'cite-source',
    label: 'Cite Source',
    shortLabel: 'Cite',
    icon: '🔬',
    description: 'Generate academic citation references (APA, MLA, IEEE).',
    mobilePriority: 12,
    desktopPriority: 12,
  },
  {
    id: 'ask-faculty',
    label: 'Ask Faculty Member',
    shortLabel: 'Ask Faculty',
    icon: '👨‍🏫',
    description: 'Forward selection as a question payload to course staff.',
    allowedModules: ['assignments', 'courses'],
    allowedRoles: ['student'],
    mobilePriority: 13,
    desktopPriority: 13,
  },
  {
    id: 'copy',
    label: 'Copy to Clipboard',
    shortLabel: 'Copy',
    icon: '✂️',
    description: 'Copy selected text directly to clipboard.',
    mobilePriority: 14,
    desktopPriority: 14,
  },
  {
    id: 'share',
    label: 'Share Selection',
    shortLabel: 'Share',
    icon: '📤',
    description: 'Email or copy link payload to chat threads.',
    mobilePriority: 15,
    desktopPriority: 15,
  },
];
